# Generated by Django 4.2 on 2023-05-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userbase_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
