# Generated by Django 4.2 on 2023-05-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
