# Generated by Django 4.2 on 2023-05-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_description_alter_product_name'),
        ('wishList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wishlist_items', to='products.product'),
        ),
    ]
