# Generated by Django 4.2 on 2023-05-15 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_description_alter_product_name'),
        ('wishList', '0002_alter_wishlist_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product_name',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
        ),
    ]
