# Generated by Django 4.2 on 2023-05-18 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 21, 50, 41, 521166, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
