# Generated by Django 4.2 on 2023-05-19 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 18, 21, 57, 875361, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
