<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-05-20 06:07
=======
# Generated by Django 4.2 on 2023-05-19 23:02
>>>>>>> 5c5376c09d134878c0312d7e8ba63eca904adeca

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 6, 7, 39, 584434, tzinfo=datetime.timezone.utc), editable=False),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 23, 2, 16, 952420, tzinfo=datetime.timezone.utc), editable=False),
>>>>>>> 5c5376c09d134878c0312d7e8ba63eca904adeca
        ),
    ]
