# Generated by Django 4.2 on 2023-05-15 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 20, 52, 53, 916379, tzinfo=datetime.timezone.utc)),
        ),
    ]
