# Generated by Django 4.2 on 2023-05-15 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_orderitems_user_alter_order_delivered_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 21, 34, 15, 371135, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
