# Generated by Django 4.2 on 2023-05-15 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_remove_orderitems_user_alter_order_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 21, 48, 39, 597838, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
