<<<<<<< HEAD
# Generated by Django 4.2 on 2023-05-16 00:30
=======
# Generated by Django 4.2 on 2023-05-16 02:28
>>>>>>> d2823f1350ba5fe5e3891a3a3481f17c999cee23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_order_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 0, 30, 35, 508080, tzinfo=datetime.timezone.utc), editable=False),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 2, 28, 5, 659903, tzinfo=datetime.timezone.utc), editable=False),
>>>>>>> d2823f1350ba5fe5e3891a3a3481f17c999cee23
        ),
    ]
