<<<<<<< HEAD
# Generated by Django 4.2 on 2023-05-16 16:05
=======
# Generated by Django 4.2 on 2023-05-16 15:30
>>>>>>> cbd022bb2675e5ded3e138611e48bbc68b46c5df

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_alter_order_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 16, 5, 8, 46255, tzinfo=datetime.timezone.utc), editable=False),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 15, 30, 2, 485670, tzinfo=datetime.timezone.utc), editable=False),
>>>>>>> cbd022bb2675e5ded3e138611e48bbc68b46c5df
        ),
    ]
