# Generated by Django 4.2 on 2023-05-16 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_order_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 15, 50, 57, 404835, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
