<<<<<<< HEAD
# Generated by Django 4.2 on 2023-05-16 16:56
=======
# Generated by Django 4.2 on 2023-05-16 15:50
>>>>>>> cbd022bb2675e5ded3e138611e48bbc68b46c5df

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_order_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 16, 56, 19, 744962, tzinfo=datetime.timezone.utc), editable=False),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 15, 50, 57, 404835, tzinfo=datetime.timezone.utc), editable=False),
>>>>>>> cbd022bb2675e5ded3e138611e48bbc68b46c5df
        ),
    ]
