<<<<<<< HEAD
# Generated by Django 4.2 on 2023-05-16 22:00
=======
# Generated by Django 4.2 on 2023-05-16 19:25
>>>>>>> fba233b64d607def6fe8fa360be25f760f932f88

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_alter_order_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 22, 0, 17, 386579, tzinfo=datetime.timezone.utc), editable=False),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 19, 25, 41, 205679, tzinfo=datetime.timezone.utc), editable=False),
>>>>>>> fba233b64d607def6fe8fa360be25f760f932f88
        ),
    ]
