# Generated by Django 4.2 on 2023-05-16 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_alter_order_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 22, 7, 37, 56762, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
