<<<<<<< HEAD
# Generated by Django 4.2 on 2023-05-16 22:07
=======
# Generated by Django 4.2 on 2023-05-16 22:09
>>>>>>> 68d6be09ed78b5900a44a8b9e8fedd9256d87d29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_alter_order_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 22, 7, 37, 56762, tzinfo=datetime.timezone.utc), editable=False),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 22, 9, 44, 972103, tzinfo=datetime.timezone.utc), editable=False),
>>>>>>> 68d6be09ed78b5900a44a8b9e8fedd9256d87d29
        ),
    ]
