# Generated by Django 4.2 on 2023-05-17 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_alter_order_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 23, 44, 36, 969447, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
