# Generated by Django 4.2 on 2023-05-18 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_alter_order_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 14, 23, 11, 368857, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
