# Generated by Django 4.2 on 2023-05-20 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishLists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wishlists',
            table='wishLists',
        ),
    ]
